name: test echo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    
    - name: get ARTIFACT_VERSION
      run: |
        REF_NAME=${{ github.ref_name }}
        echo "ARTIFACT_VERSION=${REF_NAME#v}" >> $GITHUB_ENV
    
    - name: echo
      run: |
        echo "REF_NAME: $REF_NAME"
        echo "ARTIFACT_VERSION: $ARTIFACT_VERSION"
    
